name: Publish GitHub Nuget package

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build and Generate Nuget package
        run: |
          dotnet pack -c Release -o out
          
      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source "https://nuget.pkg.github.com/EricAgnitsch/index.json" --name "githubfeed" --username "ericagnitsch.dev@gmail.com" --password "${{secrets.GH_PACKAGE_PAT}}" --store-password-in-clear-text
        
      - name: Publish Nuget Package to GitHub Packages
        run: |
          dotnet nuget push "bin/Debug/Autom8.Lib.1.0.0.nupkg" --api-key "${{secrets.GH_PACKAGE_PAT}}" --source "githubfeed"